### ISSUE TITLE
Post-Processors export template

### ISSUE THREAD

**Issue by MJA1** [jetbrains-infra/packer-builder-vsphere#49] opened 2018-01-17 09:49 UTC
Hello,

Is there a way to export the created template via packer vsphere plugin in post-processing as binary (ova, ovf, ...)?
...
"post-processors":[
   {
      "type": "compress",
      "output": "bundle.zip"
  }
  ]

Kind Regards,
Makram.

**Comment by mkuzmin** [comment] 2018-01-17 13:16
Hi Makram!

Thank you for the feedback! I'm going to close this issue as a duplicate of #34.
It would be helpful if you explain the use case, how exactly are you going to use such exported files.

**Closed by mkuzmin** 2018-01-17 13:16 UTC
Labels: duplicate
