### ISSUE TITLE
Pre-seed file and vSphere 6.0

### ISSUE THREAD

**Issue by casey-robertson** [jetbrains-infra/packer-builder-vsphere#70] opened 2018-03-21 00:36 UTC
Ran into an issue where the boot_command section does not work against our vSphere environment (6.0).  

`Build 'vsphere-iso' errored: error typing a boot command: ServerFaultCode: Unable to resolve WSDL method name PutUsbScanCodes for namespace name urn:vim25

while parsing SOAP body
at line 2, column 60

while parsing SOAP envelope
at line 2, column 0

while parsing HTTP request before method was determined
at line 1, column 0`

Looks like this method was not present in the API until vSphere 6.5.  Any workarounds?  I added this but it doesn't seem to work (hoping the machine would boot from floppy)

"floppy_files": [
        "./scripts/ubuntu/preseed.cfg"
      ],

**Comment by seanmalloy** [comment] 2018-03-21 01:26
This is a duplicate of #63. This issue should be closed.

**Comment by casey-robertson** [comment] 2018-03-21 02:00
Apologies - need to search harder.  Bugging our VM admins to upgrade test environment to 6.5.

**Comment by seanmalloy** [comment] 2018-03-21 03:02
@casey-robertson no worries. Good luck with the 6.5 upgrade.

**Closed** 2018-03-21 06:22 UTC
