### ISSUE TITLE
resource pool not found

### ISSUE THREAD

**Issue by ramonskie** [jetbrains-infra/packer-builder-vsphere#31] opened 2017-08-14 08:19 UTC
we have no resource pool defined in our vsphere because drs is not enabled
as i'm reading your documentation `resource_pool - by default a root of vSphere host.`
a resource pool seems not mandatory.

can you please elaborate on this?

```
1502442765,,ui,say,==> vsphere: Cloning VM...
1502442783,,ui,error,Build 'vsphere' errored: resource pool '/Interxion MAD2/host/10.xx.111.xxx/Resources/' not found
1502442783,,error-count,1
1502442783,,ui,error,\n==> Some builds didn't complete successfully and had errors:
1502442783,vsphere,error,resource pool '/Interxion MAD2/host/10.x.111.xxx/Resources/' not found
1502442783,,ui,error,--> vsphere: resource pool '/Interxion MAD2/host/10.xx.111.xxx/Resources/' not found
1502442783,,ui,say,\n==> Builds finished but no artifacts were created.
```

json:
```
          {
            "type" => "vsphere",
            "vcenter_server" => Stemcell::Builder::validate_env('VCENTER_SERVER'),
            "username" => Stemcell::Builder::validate_env('VCENTER_USERNAME'),
            "password" => Stemcell::Builder::validate_env('VCENTER_PASSWORD'),
            "insecure_connection" => true,

            "template" => Stemcell::Builder::validate_env('BASE_TEMPLATE'),
            "folder" => Stemcell::Builder::validate_env('VCENTER_VM_FOLDER'),
            "vm_name" =>  "packer-vmx-#{Time.now.getutc.to_i}",
            "host" =>     Stemcell::Builder::validate_env('VCENTER_HOST'),

            "ssh_username" => 'Administrator',
            "ssh_password" => Stemcell::Builder::validate_env('ADMINISTRATOR_PASSWORD'),
            "CPUs" => ENV.fetch('MEM_SIZE', '4096'),
            "RAM"  => ENV.fetch('NUM_VCPUS', '4')
          }

**Comment by mkuzmin** [comment] 2017-08-14 20:25
This is a raw error message from vSphere API. Even if you don't use pools, that just means an empty "root" pool on a host.

Do you group hosts into folders? Then a full path should be specified, like `folder/subfolder/10.5.111.5`

**Comment by ishashchuk** [comment] 2017-08-14 21:38
@mkuzmin I'm having the same issue as desribed above. We do not group hosts into folders. When the host is a member of the cluster, RP can not be found. When the host is out of the cluster and nested directly under datacenter, the "root" resource pool works just fine.

I've tried adding cluster name to the path, like cluster_name/host, but the RP still wasn't found. Do you have an idea what could be the reason, or what would the right way to specify the path to the rp that is a member of the cluster?

Thanks!

**Comment by mkuzmin** [comment] 2017-08-14 23:15
Actually, we didn't test the plugin with clusters at all.

Let me ask a stupid question, just to better understand the use case. Clustering and high availability is required for running production VMs, but here we are generating templates. What is a reason to build them on a clustered node?

**Comment by ramonskie** [comment] 2017-08-15 10:12
if browse to `hosts and clusters` it looks like
* vmware IP
  * Interxion MAD2
    * cluster1
      * 10.xx.111.xxx

**Comment by ishashchuk** [comment] 2017-08-15 19:26
@mkuzmin 
There is no reason to build them on a clustered node, since this is a just a template. It's just all hosts in our environment are clustered and are used to run production workloads. I wouldn't want to dedicate a single node for building templates(not efficient use of resources) , that's why I would like to use something that is already available. 

In my opinion, building against the cluster is a good approach, since it is more flexible. If one host is down, in Maintenance Mode or whatever, the template can be built on any other node in the cluster.  

However, as mentioned above, it looks like specifying the cluster name instead of host does the trick. Since there is always a root (Resources) resource pool on the cluster, your code works, which is perfect.

**Comment by ishashchuk** [comment] 2017-08-15 19:26
@mkuzmin 
There is no reason to build them on a clustered node, since this is a just a template. It's just all hosts in our environment are clustered and are used to run production workloads. I wouldn't want to dedicate a single node for building templates(not efficient use of resources) , that's why I would like to use something that is already available. 

In my opinion, building against the cluster is a good approach, since it is more flexible. If one host is down, in Maintenance Mode or whatever, the template can be built on any other node in the cluster.  

However, as mentioned above, it looks like specifying the cluster name instead of host does the trick. Since there is always a root (Resources) resource pool on the cluster, your code works, which is perfect.

**Comment by mkuzmin** [comment] 2017-08-15 21:45
Thank you for feedback.

I've reproduced it locally. For now I've updated README, but specifying a cluster name in `host` parameter is really confusing. Maybe we need to declare a separate parameter, just for clarity.

Another issue I fould is `A component of the virtual machine is not accessible on the host` error if a target datastore is not specified.

**Comment by ramonskie** [comment] 2017-08-16 08:58
@mkuzmin it gets even weirder
when no packer log level is defined no issues

when setting `PACKER_LOG=1` 
i get `Unable to access the virtual machine configuration: Unable to access file`

when i set `PACKER_LOG=10`
it works as designed

**Comment by mkuzmin** [comment] 2017-08-16 09:36
@ramonskie I'm a bit lost. is it about the same issue? 
Could you post a full json-config and logs into a gist, or send them to michael.kuzmin@jetbrains.com please.

**Comment by ramonskie** [comment] 2017-08-16 09:46
this is the json i use https://gist.github.com/ramonskie/371ff2907bd62dec00fd9c3f77b3bf47

the only difference is when i set the `PACKER_LOG` degug level
as seen in the same gist

**Comment by mkuzmin** [comment] 2017-08-16 11:41
yes, please open a separate issue. I'm glad to help

**Comment by ramonskie** [comment] 2017-09-14 10:19
since the latest version i get the error:
```
2017/09/13 13:42:55 [INFO] (telemetry) found error: path '/Interxion MAD2/host/cluster1' resolves to multiple hosts
1505310175,,ui,error,Build 'vsphere' errored: path '/Interxion MAD2/host/cluster1' resolves to multiple hosts
```

it worked on v.1.3.1.dev1 & v.1.3

**Comment by ramonskie** [comment] 2017-09-14 10:25
seems to be an issues with the `HostSystem` option as this does such checks
https://github.com/jetbrains-infra/packer-builder-vsphere/blob/a12121616df50a6e1d0dfd570620e132048b7771/driver/host.go#L23

**Comment by mkuzmin** [comment] 2017-09-14 11:54
Ramon, thank you for feedback, and sorry for the breaking change.
This is 3rd independent problem in the same thread. Please open a separate issue - this will help both me and other users of the tool.

**Comment by mkuzmin** [comment] 2017-09-19 12:29
I'm going to close this. Proper cluster support will be added as part of #38

**Closed by mkuzmin** 2017-09-19 12:29 UTC
Labels: problem

**Comment by alingrecea** [comment] 2017-11-03 14:13
I have been trying the plugin but I cannot get it to work. I am experiencing the same issue, .'./resources' not found. I have been fiddling with the paths:

"datacenter": "Test-DC",
    
        "host":    
        "resource_pool": "",
        
        "datastore": "",

Regardless of what I am doing it still add the "resources" word to the path where I am trying to place the virtual machine, therefore I get a path not found, error. 

I have been combing trough the discussions about this issue, but I cannot seem to get it to work.
