### ISSUE TITLE
Clusters are not supported

### ISSUE THREAD

**Issue by ramonskie** [jetbrains-infra/packer-builder-vsphere#38] opened 2017-09-14 14:37 UTC
since the latest version i get the error:
```
2017/09/13 13:42:55 [INFO] (telemetry) found error: path '/Interxion MAD2/host/cluster1' resolves to multiple hosts
1505310175,,ui,error,Build 'vsphere' errored: path '/Interxion MAD2/host/cluster1' resolves to multiple hosts
```
seems to be an issues with the `HostSystem` option as this does such checks
https://github.com/jetbrains-infra/packer-builder-vsphere/blob/a12121616df50a6e1d0dfd570620e132048b7771/driver/host.go#L23

it worked on `v.1.3.1.dev1` & `v.1.3`

maby a possibility to release `1.3.1`?? as it seems you have removed ` v.1.3.1.dev1`

**Comment by ramonskie** [comment] 2017-09-19 11:31
can i help you out with this?
i tried to build 1.3.1.dev (to fix my issue temporary) locally but it fails on a dependency

**Comment by mkuzmin** [comment] 2017-09-19 12:29
sorry for the delay. I'm at HashiConf this week. So the proper fix will take a couple of weeks.

Deleting a previous release was definitely a mistake. I've published the binaries at https://github.com/jetbrains-infra/packer-builder-vsphere/releases/tag/v1.3.1

**Comment by mkuzmin** [comment] 2017-09-28 05:50
I've reproduced the issue locally, and working on the fix.
For now yo can use a workaround: specify `datastore` for a target VM explicitly.

**Comment by alingrecea** [comment] 2017-11-03 14:37
In regards to the SSH portion under builders,

does my template need to have already ssh installed, or do I need to use a file provisioner to install it because the Building Process hangs waiting for SSH to become available. And if I want to remove from the template the SSH portion it doesn't work anymore.

Can the ssh portion be replaced with Powershell?

Moreover SSH cannot become available without an IP address, Where Can I specify The IP address subnet mask, gateway, and VLAN on which the VM should be placed?


I had to cancel the build because It was getting hung up on SSH:

==> vsphere: Pausing after run of step 'StepConnect'. Press enter to continue.
==> vsphere: Cloning VM...
==> vsphere: Pausing after run of step 'StepCloneVM'. Press enter to continue.
==> vsphere: Pausing after run of step 'StepConfigureHardware'. Press enter to continue.
==> vsphere: Power on VM...
==> vsphere: Waiting for IP...
==> vsphere: IP address: 169.254.201.214
==> vsphere: Pausing after run of step 'StepRun'. Press enter to continue.
==> vsphere: Waiting for SSH to become available...
==> vsphere: Pausing before cleanup of step 'StepRun'. Press enter to continue. ==> vsphere: Power off VM...
==> vsphere: Pausing before cleanup of step 'StepConfigureHardware'. Press enter to continue. ==> vsphere: Pausing before cleanup of step 'StepCloneVM'. Press enter to continue. ==> vsphere: Destroying VM...
==> vsphere: Pausing before cleanup of step 'StepConnect'. Press enter to continue. Build 'vsphere' errored: Build was cancelled.

**Comment by mkuzmin** [comment] 2017-11-06 15:01
@alingrecea your questions probably don't relate to clusters, please open a separate issue to continue this thread.

At the moment the plugin does not allow creating new VMs and install OS. We've started working on this feature, subscribe to #16 for updates.
You can pre-install SSH server to a base template to make it work, but a native Windows remoting protocol is WinRM, it will be supported in #12.

**Comment by alingrecea** [comment] 2017-11-06 15:25
@mkuzmin 

Thank you for your response. It did clarify some things.

**Comment by dscowan** [comment] 2017-12-28 16:39
Any update on a fix for this?

**Comment by karlikylan** [comment] 2018-02-21 20:24
Similar issue seems to be present in v2.0-beta2.

--> vsphere-iso: error creating vm: path '/Lab/host/Lab' resolves to multiple hosts
      "datacenter": "Lab",   
      "host":     "Lab",     <-- Real cluster name, with many hosts. DRS is enabled

Any workarounds for it?

**Comment by ideologysec** [comment] 2018-02-28 20:23
I'm also unable to build ubuntu VMs using the vsphere-iso builder at the present time (using version 2.0 beta2, packer 1.1.3).

I have vcenter_server, datacenter, datastore, and host set, but I get the following error:
`Build 'vsphere-iso' errored: error creating vm: resource pool '/Datacenter/host/hostname.mycompany.com/Resources/' not found`

**Comment by seanmalloy** [comment] 2018-03-03 04:50
@ideologysec I am seeing the same behavior that you are seeing. Same errors about invalid resource pool. Using version 2.0 beta2. It looks like I am not able to use this plugin in my environment because of this issue.

@mkuzmin are you working for a fix on this? Or do you need someone to step up and help fix this? I'd be willing to try and fix this. Just don't want to duplicate efforts.

**Comment by mkuzmin** [comment] 2018-03-03 10:11
At the moment my first priority is finishing ISO builder. I very appreciate any help here!

**Comment by ideologysec** [comment] 2018-03-03 15:01
I'll take a look at this and the govmomi api when I can - probably Monday.

**Comment by seanmalloy** [comment] 2018-03-05 06:28
@ideologysec let me know if I can be of any assistance. I'm willing to help with this. I probably won't be available to commit much time to this until the middle or March(a few weeks out).

**Closed** 2018-03-15 21:53 UTC
Labels: bug

**Comment by mkuzmin** [comment] 2018-03-15 22:37
I've published binaries in [v2.0-beta4](https://github.com/jetbrains-infra/packer-builder-vsphere/releases/tag/v2.0-beta4).
details on the syntax in #61.

I think now we are ready for an official release. I hope I'll publish it next week.

**Comment by troxil** [comment] 2018-03-19 05:11
Just letting you know @mkuzmin I've tested on my side using vsphere-clone and it's working great. 
Clones, waits for ssh logs in and continues as normal. 

Although not directly related - are there environment variables you can read from for the various Creds?

**Comment by mkuzmin** [comment] 2018-03-19 07:40
I don't understand the question. Feel free to open a separate issue
